export const images = {
  WalkthroughImage1: require('./walkthrough1.png'),
  WalkthroughImage2: require('./walkthrough2.png'),
  WalkthroughImage3: require('./walkthrough3.png'),
  Begin: require('./begin.png'),
  AuthenticationBackground: require('./authentication-background.png'),
  BackgroundSuccess: require('./background-success.png'),
  BackgroundError: require('./background-error.png'),
  MainBackground: require('./main-background.png'),
  DefaultAvatar: require('./default-avatar.png'),
  KingPenguin: require('./king-penguin.png'),
  ReadingActivity: require('./reading-activity.png'),
  Watching: require('./watching-activity.png'),
  History: require('./history.png'),
  DefaultBook: require('./default-book.png'),
};
